### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by tsarn** [kizz12/KOS#1]
You can run `/rom/programs/edit /users` and set your access level to whatever you want(no matter what access level you have now)

You can run `rm *` to delete everything(no matter what access level you have)

**Comment by kizz12** [comment]
Thanks for pointing this out, working on it now :dancer:

**Comment by kizz12** [comment]
I have overridden the delete command but I cannot currently find a suitable alternative for disabling /rom/programs/edit  etc. I could run a listener to listen for that exact command, but in essence, you still have to log in to do any of this. Which means either you don't use guest accounts, or be cautious who you allow guest accounts.
