### ISSUE TITLE
Can't use "edit" and "rm" other than in root directory

### ISSUE THREAD

**Issue by tsarn** [kizz12/KOS#2]
Can't use "edit" and "rm" other than in root directory

**Comment by kizz12** [comment]
I doubt this will change. You can still edit FROM the root directory and call the edit files from /edit filename. 

If you're able to write a program to use fs and edit OS files, then you shouldn't be able to log in. If you're allowing a user into the OS that can do this, then it is your own security flaw. I would have to disable the entire FS api to fix that.
